future: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: UoB Computer Science Society
description: The Computer Science Society at the University of Birmingham. 🎉🎉
url: cssbham.com
social:
  name: CSS
  links:
    - https://twitter.com/CSSBham
    - https://github.com/CSSUoB
freshers_banner:
  enabled: true
  link: /freshers
  image: /assets/images/freshers-2026/freshers-week-2026-lockup.png
menu:
  - name: FRESHERS
    link: /freshers
    class: freshers-nav
    image: /assets/images/freshers-2026/freshers-week-2026-lockup.png
    image_alt: Freshers Week
  - name: News
    link: /newsletter
  - name: Events
    link: /events
    children:
      - name: Calendar
        link: /calendar
  - name: Ball
    link: /ball
    children:
      - name: 2026
        link: /ball/2026
      - name: 2025
        link: /ball/2025
      - name: 2024
        link: /ball/2024
      - name: 2023
        link: /ball/2023
      - name: 2022
        link: /ball/2022
      - name: 2021
        link: /ball/2021
      - name: 2020
        link: /ball/2020
  - name: Merch
    link: /merch
  - name: Committee
    link: /committee
  - name: Sponsor
    link: /sponsor
  - name: About
    link: /about
    children:
      - name: Membership
        link: /membership
      - name: Links
        link: /links
baseurl: /
root: /

collections_dir: _collections/
collections:
  news:
    output: true
    permalink: /newsletter/:title
  merch:
    output: true
    permalink: /merch/:slug
  clubs:
  events:
    sort_by: order
  freshers_events:
    output: false
    sort_by: date

feed:
  collections:
    news:
      path: "/newsletter/feed.xml"

include: ["_redirects"]
keep_files: ["_redirects"]
